feat: create invite
hngprojects/hng_boilerplate_golang_web pull request #143
Opened 2024-07-24 22:09 UTC by Micah-Shallom

## Description
Implemented an API endpoint to generate invitation links for inviting users to join an organization. This endpoint validates the input data, ensures proper authorization, and generates a unique invitation link for the specified organization. The invitation link is stored in the database with an expiration date, and optionally, an email containing the invitation link is sent to the specified email address.
​
## Related Issue (Link to Github issue)

https://github.com/hngprojects/hng_boilerplate_golang_web/issues/108#issue-2424090317
​
## How Has This Been Tested?

The changes have been tested using the Go testing framework. The test environment was set up with Gin in test mode, mock data was created, and test cases for the CreateInvite function were executed. These tests ensured the validation of inputs, user authorization checks, and correct generation of invitation links. Various scenarios were tested, including successful invitation creation, invalid email format, missing organization ID, and unauthorized user.
​
## Screenshots 
![hng](https://github.com/user-attachments/assets/34684eac-5f99-4cd2-a1d6-263563a42aa8)

![a2](https://github.com/user-attachments/assets/da0e4f18-9529-4ba0-952d-40d7284e7aa1)

![a3](https://github.com/user-attachments/assets/aa9c49ef-4e4a-4daa-ade7-8337b8904a48)

![a4](https://github.com/user-attachments/assets/8e60c495-9fef-44c5-a988-b78d6012887e)

![a5](https://github.com/user-attachments/assets/4a7600ba-9edb-4378-923a-af0c7fc6c0c9)

![hng](https://github.com/user-attachments/assets/63bcb04a-4c37-44ea-b2df-8d5e68f499a7)

​
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2024-07-24 22:52 UTC, Cyberguru1 approved these changes, later dismissed
all good

2024-07-25 03:58 UTC, NwokoyeChigozie requested changes

2024-07-25 03:58 UTC, NwokoyeChigozie commented on internal/models/organisation.go
> +	}
stop stressing me nah, just follow instructions

2024-07-25 03:58 UTC, NwokoyeChigozie commented on pkg/controller/invite/postInvite.go
> +
clean up comments

2024-07-25 03:58 UTC, NwokoyeChigozie commented on tests/base.go
> +// }
clean up comments

2024-07-25 03:58 UTC, NwokoyeChigozie commented on tests/test_invites/invite_test.go
> +// }
please clean up comments

2024-07-25 05:24 UTC, Micah-Shallom commented on tests/test_invites/invite_test.go
> +// }
All highlighted issues has been corrected

2024-07-25 06:30 UTC, buka4rill commented on tests/test_invites/invite_test.go
> +// func TestPostInvite(t *testing.T) {
Remove all these irrelevant comments

2024-07-25 06:31 UTC, buka4rill commented on tests/test_invites/invite_test.go
> +
Remove this irrelevant comment

2024-07-25 06:31 UTC, buka4rill commented on tests/test_invites/invite_test.go
> +			// Message:      "Failed to parse request body",
Remove this irrelevant comment

2024-07-25 06:31 UTC, buka4rill reviewed
Take away spaghetti comments

2024-07-25 07:34 UTC, Micah-Shallom commented
@buka4rill @NwokoyeChigozie fixed issues

2024-07-26 08:01 UTC, NwokoyeChigozie requested changes

2024-07-26 08:01 UTC, NwokoyeChigozie commented on services/invite/checker.go
> +	return org, nil
service function should not be doing c.JSON for any reason

2024-07-26 08:01 UTC, NwokoyeChigozie commented on services/invite/checker.go
> +}
service function should not be doing c.JSON for any reason

2024-07-26 08:01 UTC, NwokoyeChigozie commented on services/invite/generator.go
> +	return invitationLink, nil
service function should not be doing c.JSON for any reason

2024-07-27 22:09 UTC, merged