Feat/edit product
hngprojects/hng_boilerplate_golang_web pull request #196
Opened 2024-07-29 15:58 UTC by urizennnn

## Description
Implements an endpoint `PUT /api/v1/products` that fetches product details.
​
## Related Issue (Link to Github issue)
closes #123 
​
## How Has This Been Tested?
It has been tested using postman

## Screenshots (if appropriate - Postman, etc):
### **​Success Response**
![image](https://github.com/user-attachments/assets/a00405c0-b18f-423c-b27c-d0742e0def82)

### **Product not found response**
![image](https://github.com/user-attachments/assets/8fabef66-1184-4d73-bbee-a5446acf7340)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [] Breaking change 
​
## Checklist:

- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly.
- [] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2024-07-29 19:52 UTC, Cyberguru1 requested changes

2024-07-29 19:52 UTC, Cyberguru1 commented on tests/test_product/product_test.go
> +// 	}
remove this comments if you don't need them again

2024-07-30 07:30 UTC, Cyberguru1 commented
Please add more description to this PR

2024-07-30 09:59 UTC, urizennnn commented
> Please add more description to this PR

done i will close the other one since the entire changes are present here too

2024-07-30 11:21 UTC, Cyberguru1 approved these changes
lgtm

2024-07-30 11:22 UTC, merged