[FEAT] Database Setup - Models, and Seeding
hngprojects/hng_boilerplate_golang_web pull request #43
Opened 2024-07-19 23:01 UTC by Micah-Shallom

@NwokoyeChigozie 

Setup Database initialization and seeding 

https://github.com/hngprojects/hng_boilerplate_golang_web/issues/42#issue-2420187585

2024-07-20 10:44 UTC, NwokoyeChigozie requested changes

2024-07-20 10:44 UTC, NwokoyeChigozie commented on internal/models/organisation.go
> +}
This should have been done with a receiver
func (u *User)AddToOrganisation(db *gorm.DB, orgs []interface{})
is not a bad place to start. and this should be in the user.go

2024-07-20 10:44 UTC, NwokoyeChigozie commented on services/seed/seed.go
> +		return userResp, errors.New("user id does not exist")
I don't know why you are doing this here, but it is very wrong,
if this user exists in the db, why not use the actual record id to find the record? why hardcode this here?

2024-07-20 10:44 UTC, NwokoyeChigozie commented on services/seed/seed.go
> +	userIDStr := c.Param("user_id")
get this from the controller, not the service

2024-07-20 10:44 UTC, NwokoyeChigozie commented on services/seed/seed.go
> +	if err := db.Preload("Profile").Preload("Products").Preload("Organisations").Where("email = ?", userEmail).First(&userResp).Error; err != nil {
this should be in the user model

2024-07-20 11:25 UTC, Micah-Shallom commented
@NwokoyeChigozie ... Changes has been affected Sir...Kindly review modifications.

2024-07-20 12:10 UTC, NwokoyeChigozie approved these changes

2024-07-20 12:10 UTC, merged

2024-07-21 13:37 UTC, Micah-Shallom commented
This PR was worked on by @Micah-Shallom slackID- stonepillar  and @Cyberguru1 slackID- cyberguru